[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "benchmarKIN"
license = {text = "gpl-3.0-only"}
authors = [{name = "Sophia Müller-Dott", email = "sophia.mueller-dott@uni-heidelberg.de"}]
dynamic = ["version", "description"]
